language: r
warnings_are_errors: true
sudo: required

apt_packages:
    - libcgal-dev
    - libgmp3-dev

r:
    #- devel
    - release

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
